// app/api/export-pdf/route.ts
import { createClient } from '@/lib/supabase/server'
import { NextResponse, type NextRequest } from 'next/server'

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const dateFrom      = searchParams.get('from')  ?? ''
  const dateTo        = searchParams.get('to')    ?? ''
  const selectedGroup = searchParams.get('group') ?? ''
  const lang          = searchParams.get('lang')  ?? 'fr'

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new NextResponse('Unauthorized', { status: 401 })

  const { data: profile } = await supabase
    .from('profiles').select('school_id, name').eq('id', user.id).single()

  const { data: school } = await supabase
    .from('schools').select('name, city').eq('id', profile?.school_id).single()

  const { data: rows } = await supabase
    .from('attendance')
    .select(`status, reason,
      students(name, massar_code, groups(name)),
      class_sessions!inner(session_date,
        teacher_planning!inner(start_time, end_time, group_id,
          groups(name), courses(name)))`)
    .gte('class_sessions.session_date', dateFrom)
    .lte('class_sessions.session_date', dateTo)

  const valid    = (rows ?? []).filter((r: any) => r.class_sessions?.session_date)
  const filtered = selectedGroup
    ? valid.filter((r: any) => r.class_sessions?.teacher_planning?.group_id === selectedGroup)
    : valid

  const total   = filtered.length
  const present = filtered.filter((r: any) => r.status === 'present').length
  const absent  = filtered.filter((r: any) => r.status === 'absent').length
  const late    = filtered.filter((r: any) => r.status === 'late').length
  const rate    = total > 0 ? Math.round(((present + late) / total) * 100) : 0

  const absenceRows = filtered
    .filter((r: any) => r.status === 'absent' || r.status === 'late')
    .map((r: any) => ({
      student: r.students?.name ?? '—',
      massar:  r.students?.massar_code ?? '—',
      group:   r.students?.groups?.name ?? r.class_sessions?.teacher_planning?.groups?.name ?? '—',
      course:  r.class_sessions?.teacher_planning?.courses?.name ?? '—',
      date:    new Date(r.class_sessions.session_date + 'T00:00:00').toLocaleDateString(
        lang === 'ar' ? 'ar-MA' : lang === 'en' ? 'en-GB' : 'fr-FR',
        { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' }
      ),
      time:    (r.class_sessions?.teacher_planning?.start_time?.slice(0,5) ?? '') + '–' +
               (r.class_sessions?.teacher_planning?.end_time?.slice(0,5) ?? ''),
      status:  r.status,
      reason:  r.reason ?? '',
    }))
    .sort((a: any, b: any) => b.date.localeCompare(a.date))

  const L: Record<string, Record<string, string>> = {
    fr: { title:"Rapport d'Assiduité", period:"Période", school:"Établissement", generatedOn:"Généré le",
      totalSessions:"Total relevés", present:"Présents", absent:"Absences", late:"Retards", rate:"Taux de présence",
      details:"Détail des absences et retards", student:"Étudiant", massar:"Massar", group:"Groupe",
      course:"Matière", date:"Date", time:"Horaire", type:"Type", reason:"Raison",
      absentLabel:"Absent", lateLabel:"Retard", noRecords:"Aucune absence enregistrée.", generatedBy:"Généré par Attendefy" },
    en: { title:"Attendance Report", period:"Period", school:"School", generatedOn:"Generated on",
      totalSessions:"Total records", present:"Present", absent:"Absences", late:"Late", rate:"Attendance rate",
      details:"Absence and late details", student:"Student", massar:"Massar", group:"Group",
      course:"Subject", date:"Date", time:"Time", type:"Type", reason:"Reason",
      absentLabel:"Absent", lateLabel:"Late", noRecords:"No absences recorded.", generatedBy:"Generated by Attendefy" },
    ar: { title:"تقرير الحضور", period:"الفترة", school:"المؤسسة", generatedOn:"تاريخ الإنشاء",
      totalSessions:"إجمالي السجلات", present:"حاضر", absent:"الغيابات", late:"التأخيرات", rate:"نسبة الحضور",
      details:"تفاصيل الغيابات والتأخيرات", student:"الطالب", massar:"مسار", group:"الفصل",
      course:"المادة", date:"التاريخ", time:"التوقيت", type:"النوع", reason:"السبب",
      absentLabel:"غائب", lateLabel:"متأخر", noRecords:"لا توجد غيابات مسجلة.", generatedBy:"تم إنشاؤه بواسطة Attendefy" },
  }

  const t   = L[lang] ?? L.fr
  const dir = lang === 'ar' ? 'rtl' : 'ltr'
  const now = new Date().toLocaleDateString(
    lang === 'ar' ? 'ar-MA' : lang === 'en' ? 'en-GB' : 'fr-FR',
    { day: 'numeric', month: 'long', year: 'numeric' }
  )
  const rateColor = rate >= 80 ? '#16a34a' : rate >= 60 ? '#d97706' : '#dc2626'

  const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
<meta charset="UTF-8"/>
<title>${t.title} — ${school?.name ?? 'Attendefy'}</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Segoe UI',Arial,sans-serif;color:#1e293b;background:#fff;font-size:13px}
  .hdr{background:#1e40af;color:white;padding:24px 32px;display:flex;justify-content:space-between;align-items:center}
  .hdr h1{font-size:20px;font-weight:700}.hdr h1 span{color:#93c5fd}
  .hdr-right{text-align:${dir==='rtl'?'left':'right'}}.hdr-right .sn{font-size:15px;font-weight:600}
  .hdr-right .mt{font-size:11px;color:#bfdbfe;margin-top:2px}
  .body{padding:20px 32px}
  .info{display:flex;gap:20px;background:#f1f5f9;border-radius:8px;padding:12px 16px;margin-bottom:20px;flex-wrap:wrap}
  .info-item label{font-size:10px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.5px;display:block}
  .info-item span{font-size:13px;font-weight:600;color:#1e293b}
  .stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:24px}
  .sc{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px;text-align:center}
  .sc .v{font-size:22px;font-weight:700}.sc .l{font-size:11px;color:#64748b;margin-top:2px}
  .sc.pr .v{color:#16a34a}.sc.ab .v{color:#dc2626}.sc.la .v{color:#d97706}.sc.rt .v{color:${rateColor}}
  h2{font-size:14px;font-weight:700;color:#1e293b;margin-bottom:10px;padding-bottom:6px;border-bottom:2px solid #e2e8f0}
  table{width:100%;border-collapse:collapse;font-size:11px}
  thead tr{background:#1e40af;color:white}
  thead th{padding:8px 9px;text-align:${dir==='rtl'?'right':'left'};font-weight:600;font-size:10.5px}
  tbody tr:nth-child(even){background:#f8fafc}
  tbody td{padding:7px 9px;border-bottom:1px solid #f1f5f9;color:#334155}
  .badge{display:inline-block;padding:2px 7px;border-radius:999px;font-size:10px;font-weight:700}
  .badge.absent{background:#fee2e2;color:#dc2626}.badge.late{background:#fef3c7;color:#d97706}
  .no-rec{text-align:center;padding:28px;color:#94a3b8;font-style:italic}
  .footer{margin-top:24px;padding:12px 32px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;color:#94a3b8;font-size:10px}
  @media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
  @page{margin:0;size:A4}
</style>
</head>
<body>
<div class="hdr">
  <div><h1>Attend<span>efy</span></h1><p style="color:#bfdbfe;font-size:11px;margin-top:2px">${t.generatedBy}</p></div>
  <div class="hdr-right"><div class="sn">${school?.name??'—'}</div><div class="mt">${school?.city??''}</div></div>
</div>
<div class="body">
  <div class="info">
    <div class="info-item"><label>${t.period}</label><span>${dateFrom} → ${dateTo}</span></div>
    <div class="info-item"><label>${t.generatedOn}</label><span>${now}</span></div>
    <div class="info-item"><label>${t.school}</label><span>${school?.name??'—'}</span></div>
  </div>
  <div class="stats">
    <div class="sc"><div class="v">${total}</div><div class="l">${t.totalSessions}</div></div>
    <div class="sc pr"><div class="v">${present}</div><div class="l">${t.present}</div></div>
    <div class="sc ab"><div class="v">${absent}</div><div class="l">${t.absent}</div></div>
    <div class="sc la"><div class="v">${late}</div><div class="l">${t.late}</div></div>
    <div class="sc rt"><div class="v">${rate}%</div><div class="l">${t.rate}</div></div>
  </div>
  <h2>${t.details}</h2>
  ${absenceRows.length === 0
    ? `<div class="no-rec">${t.noRecords}</div>`
    : `<table><thead><tr>
        <th>${t.student}</th><th>${t.massar}</th><th>${t.group}</th>
        <th>${t.course}</th><th>${t.date}</th><th>${t.time}</th>
        <th>${t.type}</th><th>${t.reason}</th>
      </tr></thead><tbody>
      ${absenceRows.map((r: any) => `<tr>
        <td><strong>${r.student}</strong></td><td>${r.massar}</td><td>${r.group}</td>
        <td>${r.course}</td><td>${r.date}</td>
        <td style="font-family:monospace">${r.time}</td>
        <td><span class="badge ${r.status}">${r.status==='absent'?t.absentLabel:t.lateLabel}</span></td>
        <td>${r.reason||'—'}</td>
      </tr>`).join('')}
      </tbody></table>`}
</div>
<div class="footer">
  <span>Attendefy — ${school?.name??''}</span>
  <span>${now}</span>
</div>
<script>window.onload=()=>{window.print()}</script>
</body>
</html>`

  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' }
  })
}